### PR TITLE
Terraform v1 Support

### PR DESCRIPTION
**Pull request by soerenmartius**
- build: upgrade build-tools to v0.12.1
- feat: add compatibility for Terraform v1
- docs: update docs to include Terraform v1
- chore: prepare v0.5.0 release

### CODE REVIEW

**Comment by mariux** [comment]
please resolve conflicts first

**Comment by mariux** [comment]
converted to draft

**Review by mariux — CHANGES_REQUESTED** [review]
please resolve conflicts by rebasing

**Comment by soerenmartius** [comment]
sorry, forgot to rebase - should be ok now

**Review by mariux — APPROVED** [review]
lgtm

**Pull request merged**
